### ISSUE TITLE
Make sure it works with new URLs

### ISSUE THREAD

**Issue by maxogden** [electron-userland/electron-prebuilt-updater#6]
Hey John,

We moved electron-prebuilt to https://github.com/electron-userland/electron-prebuilt, I just wanna open this as an FYI. Hopefully github redirects handle any URL changes and nothing breaks

**Comment by johnmuhl** [comment]
Thanks for the heads-up. I think the `OWNER` and `REPO` environment variables on the Heroku side are used to build up the URLs. If you updated those then hopefully things will keep on working. We can leave this open until the next release confirms everything is working.

**Comment by maxogden** [comment]
ah dang I forgot to update OWNER env var before this release, which is probably why it failed. Just updated it and deployed latest git version of this repo to heroku. gonna release 0.36.10 manually.

**Comment by johnmuhl** [comment]
Last two releases went off without issue.
