### ISSUE TITLE
version 0.36.10 not pushed to electron-prebuilt

### ISSUE THREAD

**Issue by ngoldman** [electron-userland/electron-prebuilt-updater#9]
Hi @johnmuhl! It looks like the update for `0.36.10` wasn't pushed to electron-prebuilt (see https://github.com/electron-userland/electron-prebuilt/issues/101). Is the service still running?

**Comment by maxogden** [comment]
trying to get heroku logs (I run it) from the train I'm on and the heroku CLI decided now was a good time to do automatic updates

```
heroku logs -n 1500 --app maxogden-electron-releaser
Updating Heroku v4 CLI to 4.27.25-3b727e5 (master)... 
```

**Comment by maxogden** [comment]
also closing b/c https://github.com/electron-userland/electron-prebuilt-updater/issues/6

**Comment by ngoldman** [comment]
:+1: thanks @maxogden
